spring:
  datasource:
    url: "${db_host}/messenger"
    driver-class-name: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

app:
  auth:
    tokenSecret: ${security_secret}
    tokenExpirationMSec: 86400000000000
    tokenPrefix: "Bearer "
    headerString: "Authorization"
    cors:
      allowedOrigins: http://localhost:8080, http://localhost:3000
